### ISSUE TITLE
Tutorial page is with empty content table

### ISSUE THREAD

**Issue by nobuto-m** [canonical-ols/snapstore-snap-docs#50]
Looks like after the change (https://github.com/canonical-ols/snapstore-snap-docs/pull/47), the page has an empty table although the leading text says it has a tutorial.

https://docs.ubuntu.com/snap-store-proxy/en/tutorial
> This section of our documentation contains step-by-step tutorials to help outline what the Snap Store Proxy is capable of while helping you achieve specific aims.

![image](https://github.com/canonical-ols/snapstore-snap-docs/assets/4356209/3a66461e-f01c-4d00-8c0e-63c7e32dc2cd)

**Comment by SecondSkoll** [comment]
Landing page has been removed as Snap Store Proxy does not have a tutorial - and none is planned.
